In [1]:
import cv2
import numpy as np
from keras.models import load_model
import os
from PIL import Image

Using TensorFlow backend.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
model=load_model('/content/drive/My Drive/Sem 7/Minior/meet parshv/My_model_V4.h5')






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.








Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




In [0]:
predicted1 = np.zeros((746,2))
predicted2 = np.zeros((743,2))

In [0]:
 def generate(image_path,video,num):
        face_cascade = cv2.CascadeClassifier('/content/drive/My Drive/Sem 7/Minior/meet parshv/cascade.xml')
        img1 = Image.open(image_path)
        img=np.array(img1)
        myimg = cv2.imread(image_path)
        if (img is None):
            print("Can't open image file")
            return 0

        #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(img, 1.1, 3, minSize=(100, 100))
        if (len(faces)==0):
            print('Failed to detect face')
            myimg=cv2.resize(myimg,(1024,700), interpolation = cv2.INTER_AREA)
            return myimg

            cv2.destroyAllWindows()

        facecnt = len(faces)
        print("Detected faces: %d" % facecnt)
        i = 0
        height, width = img.shape[:2]
        lastimg = 0
        for (x, y, w, h) in faces:
            r = max(w, h) / 2
            centerx = x + w / 2
            centery = y + h / 2
            nx = int(centerx - r)
            ny = int(centery - r)
            nr = int(r * 2)
            faceimg = img[ny:ny+nr, nx:nx+nr]
            lastimg = cv2.resize(faceimg, (32, 32))

            a=np.array(lastimg)
            a = np.expand_dims(a, axis=0)
            prediction = model.predict(a)    
            print(prediction)
            if prediction[0][0]>0.5:
                if video==1:
                    predicted1[num][0]=round((prediction[0][0])*100, 2)
                    print(predicted1[num][0])
                if video==2:
                    predicted2[num][0]=round((prediction[0][0])*100, 2)
                    print(predicted2[num][0])
            elif prediction[0][0]<0.5:
                if video==1:
                    predicted1[num][1]=round((prediction[0][1])*100, 2)
                    print(predicted1[num][1])
                if video==2:
                    predicted2[num][1]=round((prediction[0][1])*100, 2)
                    print(predicted2[num][1])


                                    
            i = i + 1

        return i

In [6]:
for i in range(746):
    generate("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame"+str(i)+".jpg",1,i)
    

Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Detected faces: 2
[[1.0000000e+00 4.7306337e-09]]
100.0
[[9.9957675e-01 4.2319795e-04]]
99.96
Failed to detect face
Detected faces: 2
[[9.9992526e-01 7.4757205e-05]]
99.99
[[9.9994147e-01 5.8477832e-05]]
99.99
Detected faces: 2
[[0.88911265 0.11088734]]
88.91
[[9.9980158e-01 1.9843227e-04]]
99.98
Detected faces: 1
[[9.9999380e-01 6.1876826e-06]]
100.0
Detected faces: 1
[[0.99787116 0.00212887]]
99.79
Detected faces: 1
[[9.9968410e-01 3.1590762e-04]]
99.97
Failed to detect face
Failed to detect face
Failed to detect face
Detected faces: 1
[[0.9857027  0.01429725]]
98.57
Detected faces: 1
[[0.9958776  0.00412233]]
99.59
Detected faces: 1
[[9.9954093e-01 4.5906624e-04]]
99.95
Detected faces: 1
[[0.04177728 0.9582228 ]]
95.82
Detected faces: 1
[[1.0000000e+00 1.2667893e-13]]
100.0
Detected faces: 2
[[9.9916208e-01 8.3790394e-04]]
99.92
[[9.9950874e-01 4.912967

In [7]:
for i in range(743):
    generate("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame"+str(i)+".jpg",2,i)

Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Failed to detect face
Detected faces: 1
[[0.02980958 0.9701904 ]]
97.02
Detected faces: 1
[[0.06631192 0.9336881 ]]
93.37
Detected faces: 1
[[0.02588555 0.9741145 ]]
97.41
Detected faces: 2
[[0.9981779  0.00182218]]
99.82
[[0.17982948 0.8201705 ]]
82.02
Detected faces: 2
[[9.9960285e-01 3.9712389e-04]]
99.96
[[0.4290529 0.5709472]]
57.09
Detected faces: 2
[[0.99542564 0.00457442]]
99.54
[[0.0676519 0.9323481]]
93.23
Detected faces: 2
[[9.9998236e-01 1.7603614e-05]]
100.0
[[0.9590492  0.04095071]]
95.9
Detected faces: 2
[[9.9996495e-01 3.5033074e-05]]
100.0
[[0.9171481  0.08285186]]
91.71
Detected faces: 1
[[1.000000e+00 3.195618e-09]]
100.0
Detected faces: 2
[[9.9996531e-01 3.4635606e-05]]
100.0
[[0.4788955 0.5211045]]
52.11
Detected faces: 2
[[9.9

In [8]:
predicted1

array([[  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       ...,
       [100.,   0.],
       [100.,   0.],
       [  0.,   0.]])

In [9]:
predicted2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
#Synchronizing Predicted_data1 and Predicted_data2 Folders According to Prediction Scores.
#Synchronized Frames are stored in Predicted_data Folder.
check=1
for i in range(746):
    str1="/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data1/frame"+str(i)+".jpg"
    str2="/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data2/frame"+str(i)+".jpg"
    if i<743 and ( predicted1[i][0]>predicted2[i][0] or predicted1[i][1]>predicted2[i][1] ):           
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame"+str(i)+".jpg",cv2.imread(str1))
        check=1
    elif i<743 and check==1 and ( predicted2[i][0]==0. and predicted2[i][1]==0.):
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame"+str(i)+".jpg",cv2.imread(str1))
    elif i<743 and check==2 and ( predicted1[i][0]==0. and predicted1[i][1]==0.):
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame"+str(i)+".jpg",cv2.imread(str2))        
    else:
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame"+str(i)+".jpg",cv2.imread(str2))
        check=2

In [0]:
from os.path import isfile, join

def convert_frames_to_video(pathIn,pathOut,fps):
    frame_array = []
    files = [f for f in os.listdir(pathIn) if isfile(join(pathIn, f))]

    #for sorting the file names properly
    files.sort(key = lambda x: int(x[5:-4]))

    for i in range(729):
        filename=pathIn + files[i]
        #reading each files
        img = cv2.imread(filename)
        height, width, layers = img.shape
        size = (width,height)
        print(filename)
        #inserting the frames into an image array
        frame_array.append(img)

    out = cv2.VideoWriter(pathOut,cv2.VideoWriter_fourcc(*'DIVX'), fps, size)

    for i in range(len(frame_array)):
        # writing to a image array
        out.write(frame_array[i])
    out.release()


In [22]:
#Converting Frames of Predicted_data to Predicted_Video.mp4
def main():
    pathIn= '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/'
    pathOut = '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_video.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame0.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame1.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame2.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame3.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame4.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame5.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame6.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame7.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame8.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame9.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame10.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data/frame11.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/A

In [0]:
#Extracting Synchronized frames which contains only parshv and storing it into predicted_parshv Folder
for i in range(729):
    str1="/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data1/frame"+str(i)+".jpg"
    str2="/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data2/frame"+str(i)+".jpg"
    if i<700 and predicted1[i][1]>0. and predicted1[i][0]==0.: 
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame"+str(i)+".jpg",cv2.imread(str1))
    elif predicted2[i][1]>0. and predicted2[i][0]==0.:
        cv2.imwrite("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame"+str(i)+".jpg",cv2.imread(str2))  

In [49]:
#Converting Frames of Predicted_Megh to Predicted_Megh_video.mp4
def main():
    pathIn= '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/'
    pathOut = '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv_video.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame12.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame13.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame14.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame19.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame25.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame27.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame37.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame101.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame235.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame236.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame237.jpg
/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_parshv/frame238.jpg
/content/dr

IndexError: ignored

In [0]:
#Extracting Synchronized frames which contains only Amish and storing it into Predicted_Amish Folder
for i in range(535):
    str1="./3 angle Video Dataset/Predicted_data1/frame"+str(i)+".jpg"
    str2="./3 angle Video Dataset/Predicted_data2/frame"+str(i)+".jpg"
    if i<506 and ( predicted1[i][0]>0. and predicted1[i][1]==0.):           
        cv2.imwrite("./3 angle Video Dataset/Predicted_Amish/frame"+str(i)+".jpg",cv2.imread(str1))
    elif predicted2[i][0]>0. and predicted2[i][1]==0.:
        cv2.imwrite("./3 angle Video Dataset/Predicted_Amish/frame"+str(i)+".jpg",cv2.imread(str2)) 

In [0]:
#Converting Frames of Predicted_Amish to Predicted_Amish_video.mp4
def main():
    pathIn= './3 angle Video Dataset/Predicted_Amish/'
    pathOut = './3 angle Video Dataset/Predicted_Amish_video.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

./3 angle Video Dataset/Predicted_Amish/frame17.jpg
./3 angle Video Dataset/Predicted_Amish/frame18.jpg
./3 angle Video Dataset/Predicted_Amish/frame21.jpg
./3 angle Video Dataset/Predicted_Amish/frame22.jpg
./3 angle Video Dataset/Predicted_Amish/frame23.jpg
./3 angle Video Dataset/Predicted_Amish/frame24.jpg
./3 angle Video Dataset/Predicted_Amish/frame25.jpg
./3 angle Video Dataset/Predicted_Amish/frame27.jpg
./3 angle Video Dataset/Predicted_Amish/frame28.jpg
./3 angle Video Dataset/Predicted_Amish/frame29.jpg
./3 angle Video Dataset/Predicted_Amish/frame30.jpg
./3 angle Video Dataset/Predicted_Amish/frame33.jpg
./3 angle Video Dataset/Predicted_Amish/frame83.jpg
./3 angle Video Dataset/Predicted_Amish/frame100.jpg
./3 angle Video Dataset/Predicted_Amish/frame101.jpg
./3 angle Video Dataset/Predicted_Amish/frame102.jpg
./3 angle Video Dataset/Predicted_Amish/frame103.jpg
./3 angle Video Dataset/Predicted_Amish/frame104.jpg
./3 angle Video Dataset/Predicted_Amish/frame105.jpg
./3 an

In [0]:
#Extracting Synchronized frames which contains only Amish & Megh Together and storing it into Predicted_Both Folder
for i in range(535):
    str1="./3 angle Video Dataset/Predicted_data1/frame"+str(i)+".jpg"
    str2="./3 angle Video Dataset/Predicted_data2/frame"+str(i)+".jpg"
    if i<506 and predicted1[i][0]>0. and predicted1[i][1]>0.:           
        cv2.imwrite("./3 angle Video Dataset/Predicted_Both/frame"+str(i)+".jpg",cv2.imread(str1))
    elif predicted2[i][1]>0. and predicted2[i][1]>0.:
        cv2.imwrite("./3 angle Video Dataset/Predicted_Both/frame"+str(i)+".jpg",cv2.imread(str2)) 

In [0]:
#Converting Frames of Predicted_Both to Predicted_Both_video.mp4
def main():
    pathIn= './3 angle Video Dataset/Predicted_Both/'
    pathOut = './3 angle Video Dataset/Predicted_Both_video.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

./3 angle Video Dataset/Predicted_Both/frame19.jpg
./3 angle Video Dataset/Predicted_Both/frame20.jpg
./3 angle Video Dataset/Predicted_Both/frame35.jpg
./3 angle Video Dataset/Predicted_Both/frame120.jpg
./3 angle Video Dataset/Predicted_Both/frame144.jpg
./3 angle Video Dataset/Predicted_Both/frame212.jpg
./3 angle Video Dataset/Predicted_Both/frame214.jpg
./3 angle Video Dataset/Predicted_Both/frame215.jpg
./3 angle Video Dataset/Predicted_Both/frame217.jpg
./3 angle Video Dataset/Predicted_Both/frame218.jpg
./3 angle Video Dataset/Predicted_Both/frame219.jpg
./3 angle Video Dataset/Predicted_Both/frame220.jpg
./3 angle Video Dataset/Predicted_Both/frame221.jpg
./3 angle Video Dataset/Predicted_Both/frame232.jpg
./3 angle Video Dataset/Predicted_Both/frame242.jpg
./3 angle Video Dataset/Predicted_Both/frame243.jpg
./3 angle Video Dataset/Predicted_Both/frame251.jpg
./3 angle Video Dataset/Predicted_Both/frame253.jpg
./3 angle Video Dataset/Predicted_Both/frame254.jpg
./3 angle Video