In [1]:
import cv2
import numpy as np
from keras.models import load_model
import os
from PIL import Image

Using TensorFlow backend.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!ls
%cd Sem 7
#%cd /content/drive/My drive/Sem 7/minior/meet parshv

drive  sample_data
[Errno 2] No such file or directory: 'Sem 7'
/content


In [3]:
model=load_model('/content/drive/My Drive/Sem 7/Minior/meet parshv/My_model_V4.h5')






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.








Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




In [9]:
#Code Block-Converting Video2 into frames and storing it into data1 folder

root_dir ='/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv'
print(root_dir)

FPS = 15
# Playing video from file:
cap = cv2.VideoCapture('/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/video1.mp4')
    #cap.set(cv2.CAP_PROP_FPS, FPS)

# try:
#     if not os.path.exists(root_dir+'/data2'):
#         os.makedirs(root_dir+'data2')
# except OSError:
#     print ('Error: Creating directory of data')
#print(root_dir+'/data1/frame' + str(currentFrame) + '.jpg')
currentFrame = 0
while(True):
    # Capture frame-by-frame
    cap.set(cv2.CAP_PROP_POS_MSEC,(currentFrame*1000/FPS))
    #cv2.waitKey(100)
   # print("hel")
    ret, frame = cap.read()
    print(ret)
    if not ret:break
      
    # Saves image of the current frame in jpg file
    name = root_dir+'/data1/frame' + str(currentFrame) + '.jpg'
    print ('Creating...' + name)
    cv2.imwrite(name, frame)

    # To stop duplicate images
    currentFrame += 1

    

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()


/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame0.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame1.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame2.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame3.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame4.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame5.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame6.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame7.jpg


KeyboardInterrupt: ignored

In [0]:
#Code Block-Converting Video2 into frames and storing it into data1 folder

root_dir ='/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv'
print(root_dir)

FPS = 15
# Playing video from file:
cap = cv2.VideoCapture('/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/video2.mp4')
    #cap.set(cv2.CAP_PROP_FPS, FPS)

# try:
#     if not os.path.exists(root_dir+'/data2'):
#         os.makedirs(root_dir+'data2')
# except OSError:
#     print ('Error: Creating directory of data')
#print(root_dir+'/data1/frame' + str(currentFrame) + '.jpg')
currentFrame = 0
while(True):
    # Capture frame-by-frame
    cap.set(cv2.CAP_PROP_POS_MSEC,(currentFrame*1000/FPS))
    #cv2.waitKey(100)
   # print("hel")
    ret, frame = cap.read()
    print(ret)
    if not ret:break
      
    # Saves image of the current frame in jpg file
    name = root_dir+'/data2/frame' + str(currentFrame) + '.jpg'
    print ('Creating...' + name)
    cv2.imwrite(name, frame)

    # To stop duplicate images
    currentFrame += 1

    

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()


/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame0.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame1.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame2.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame3.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame4.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame5.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame6.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame7.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame8.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame9.jpg
True
Creating.../content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data2/frame10.jpg


In [0]:
 def generate(image_path):
        face_cascade = cv2.CascadeClassifier('/content/drive/My Drive/Sem 7/Minior/meet parshv/cascade.xml')
        img1 = Image.open(image_path)
        img=np.array(img1)
        myimg = cv2.imread(image_path)
        if (img is None):
            print("Can't open image file")
            return 0

        #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(img, 1.1, 3, minSize=(100, 100))
        if (len(faces)==0):
            print('Failed to detect face')
            myimg=cv2.resize(myimg,(1024,700), interpolation = cv2.INTER_AREA)
            return myimg

            cv2.destroyAllWindows()

        facecnt = len(faces)
        print("Detected faces: %d" % facecnt)
        i = 0
        height, width = img.shape[:2]
        lastimg = 0
        for (x, y, w, h) in faces:
            r = max(w, h) / 2
            centerx = x + w / 2
            centery = y + h / 2
            nx = int(centerx - r)
            ny = int(centery - r)
            nr = int(r * 2)

            faceimg = img[ny:ny+nr, nx:nx+nr]
            lastimg = cv2.resize(faceimg, (32, 32))

            a=np.array(lastimg)
            a = np.expand_dims(a, axis=0)
            prediction = model.predict(a)    
            print(prediction)
            
            if prediction[0][0]>0.5:
                #If Meet is predicted, mark rectangle and put text label above it.
                faceimg=cv2.rectangle(myimg,(x,y),(x+w,y+h),(0,255,0),5)
                faceimg=cv2.putText(faceimg,'Meet-'+str(round((prediction[0][0])*100, 2)), (x,y), cv2.LINE_AA, 1.0, (255, 0, 0),3)
                faceimg=cv2.resize(myimg,(1024,700), interpolation = cv2.INTER_AREA)
            elif prediction[0][0]<0.5:
                #If Parshv is predicted, mark rectangle and put text label above it.
                faceimg=cv2.rectangle(myimg,(x,y),(x+w,y+h),(0,0,255),5)
                faceimg=cv2.putText(faceimg,'Parshv-'+str(round((prediction[0][1])*100, 2)), (x,y), cv2.LINE_AA, 1.0, (0, 0, 255),3)
                faceimg=cv2.resize(myimg,(1024,700), interpolation = cv2.INTER_AREA)
                                    
            i = i + 1

        return faceimg

In [17]:
my=generate("/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/data1/frame145.jpg")
cv2.imshow("Image",my)
cv2.waitKey(0)
cv2.destroyAllWindows()

Detected faces: 2
[[1.0000000e+00 2.3415901e-11]]
[[1.0000000e+00 3.7628025e-09]]


DisabledFunctionError: ignored

In [20]:
#Gnerating Prediction results from Video1 and storing it into Predicted_data1 folder
root_dir='/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv'
for i in range(506,746):
    im=cv2.imwrite(root_dir+"/predicted_data1/frame"+str(i)+".jpg",generate(root_dir+"/data1/frame"+str(i)+".jpg"))
    print("creating frame"+str(i))
        
        

Detected faces: 1
[[9.9999976e-01 2.7323793e-07]]
creating frame506
Detected faces: 1
[[1.0000000e+00 5.7322428e-08]]
creating frame507
Detected faces: 1
[[9.9999988e-01 1.4036677e-07]]
creating frame508
Failed to detect face
creating frame509
Detected faces: 1
[[1.0000000e+00 2.0414169e-11]]
creating frame510
Detected faces: 1
[[1.0000000e+00 2.4145128e-09]]
creating frame511
Detected faces: 1
[[9.9992812e-01 7.1898794e-05]]
creating frame512
Failed to detect face
creating frame513
Detected faces: 1
[[1.00000000e+00 1.07805125e-08]]
creating frame514
Detected faces: 3
[[1.000000e+00 9.183289e-13]]
[[9.9999917e-01 8.5322864e-07]]
[[9.9999833e-01 1.6691664e-06]]
creating frame515
Failed to detect face
creating frame516
Detected faces: 2
[[9.9998283e-01 1.7118915e-05]]
[[9.995875e-01 4.125070e-04]]
creating frame517
Failed to detect face
creating frame518
Detected faces: 1
[[9.999932e-01 6.827504e-06]]
creating frame519
Detected faces: 1
[[9.9998665e-01 1.3308825e-05]]
creating frame520


In [71]:
#Gnerating Prediction results from Video2 and storing it into Predicted_data2 folder
root_dir='/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv'
for i in range(743):
    im=cv2.imwrite(root_dir+"/predicted_data2/frame"+str(i)+".jpg",generate(root_dir+"/data2/frame"+str(i)+".jpg"))
    print("creating frame"+str(i))
        

Failed to detect face
creating frame0
Failed to detect face
creating frame1
Failed to detect face
creating frame2
Failed to detect face
creating frame3
Failed to detect face
creating frame4
Failed to detect face
creating frame5
Failed to detect face
creating frame6
Failed to detect face
creating frame7
Failed to detect face
creating frame8
Failed to detect face
creating frame9
Failed to detect face
creating frame10
Failed to detect face
creating frame11
Detected faces: 1
[[0.02980958 0.9701904 ]]
creating frame12
Detected faces: 1
[[0.06631192 0.9336881 ]]
creating frame13
Detected faces: 1
[[0.02588555 0.9741145 ]]
creating frame14
Detected faces: 2
[[0.9981779  0.00182218]]
[[0.17982948 0.8201705 ]]
creating frame15
Detected faces: 2
[[9.9960285e-01 3.9712389e-04]]
[[0.4290529 0.5709472]]
creating frame16
Detected faces: 2
[[0.99542564 0.00457442]]
[[0.0676519 0.9323481]]
creating frame17
Detected faces: 2
[[9.9998236e-01 1.7603614e-05]]
[[0.9590492  0.04095071]]
creating frame18
Det

In [0]:
#Converting Frames to Video
from os.path import isfile, join

def convert_frames_to_video(pathIn,pathOut,fps):
    frame_array = []
    files = [f for f in os.listdir(pathIn) if isfile(join(pathIn, f))]
    
    
    #for sorting the file names properly
    files.sort(key = lambda x: int(x[5:-4]))
    
    for i in range(len(files)):
        filename=pathIn+'/'+files[i]
       
        
        #reading each files
        img = cv2.imread(filename)
     #   print(img)
        height, width, layers = img.shape
        size = (width,height)
        
      #  print(filename)
        #inserting the frames into an image array
        frame_array.append(img)

    out = cv2.VideoWriter(pathOut,cv2.VideoWriter_fourcc(*'DIVX'), fps, size)

    for i in range(len(frame_array)):
        # writing to a image array
        out.write(frame_array[i])
    out.release()



In [41]:
#Converting Frames of Predicted_data1 to Predicted_Video1.mp4
def main():
    pathIn= '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data1'
    pathOut = '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/Predicted_video1.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

['frame0.jpg', 'frame1.jpg', 'frame2.jpg', 'frame3.jpg', 'frame4.jpg', 'frame5.jpg', 'frame6.jpg', 'frame7.jpg', 'frame8.jpg', 'frame9.jpg', 'frame10.jpg', 'frame11.jpg', 'frame12.jpg', 'frame13.jpg', 'frame14.jpg', 'frame15.jpg', 'frame16.jpg', 'frame17.jpg', 'frame18.jpg', 'frame19.jpg', 'frame20.jpg', 'frame21.jpg', 'frame22.jpg', 'frame23.jpg', 'frame24.jpg', 'frame25.jpg', 'frame26.jpg', 'frame27.jpg', 'frame28.jpg', 'frame29.jpg', 'frame30.jpg', 'frame31.jpg', 'frame32.jpg', 'frame33.jpg', 'frame34.jpg', 'frame35.jpg', 'frame36.jpg', 'frame37.jpg', 'frame38.jpg', 'frame39.jpg', 'frame40.jpg', 'frame41.jpg', 'frame42.jpg', 'frame43.jpg', 'frame44.jpg', 'frame45.jpg', 'frame46.jpg', 'frame47.jpg', 'frame48.jpg', 'frame49.jpg', 'frame50.jpg', 'frame51.jpg', 'frame52.jpg', 'frame53.jpg', 'frame54.jpg', 'frame55.jpg', 'frame56.jpg', 'frame57.jpg', 'frame58.jpg', 'frame59.jpg', 'frame60.jpg', 'frame61.jpg', 'frame62.jpg', 'frame63.jpg', 'frame64.jpg', 'frame65.jpg', 'frame66.jpg', 'fra

In [0]:
#Converting Frames of Predicted_data1 to Predicted_Video1.mp4
def main():
    pathIn= '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/predicted_data2'
    pathOut = '/content/drive/My Drive/Sem 7/Minior/meet parshv/Adv/Predicted_video2.mp4'
    fps = 15.0
    convert_frames_to_video(pathIn, pathOut, fps)

if __name__=="__main__":
    main()

In [0]:
#Converting Frames of Predicted_data3 to Predicted_Video3.mp4
# def main():
#     pathIn= './3 angle Video Dataset/Predicted_data3/'
#     pathOut = './3 angle Video Dataset/Predicted_video3.mp4'
#     fps = 15.0
#     convert_frames_to_video(pathIn, pathOut, fps)

# if __name__=="__main__":
#     main()

./3 angle Video Dataset/Predicted_data3/frame0.jpg
./3 angle Video Dataset/Predicted_data3/frame1.jpg
./3 angle Video Dataset/Predicted_data3/frame2.jpg
./3 angle Video Dataset/Predicted_data3/frame3.jpg
./3 angle Video Dataset/Predicted_data3/frame4.jpg
./3 angle Video Dataset/Predicted_data3/frame5.jpg
./3 angle Video Dataset/Predicted_data3/frame6.jpg
./3 angle Video Dataset/Predicted_data3/frame7.jpg
./3 angle Video Dataset/Predicted_data3/frame8.jpg
./3 angle Video Dataset/Predicted_data3/frame9.jpg
./3 angle Video Dataset/Predicted_data3/frame10.jpg
./3 angle Video Dataset/Predicted_data3/frame11.jpg
./3 angle Video Dataset/Predicted_data3/frame12.jpg
./3 angle Video Dataset/Predicted_data3/frame13.jpg
./3 angle Video Dataset/Predicted_data3/frame14.jpg
./3 angle Video Dataset/Predicted_data3/frame15.jpg
./3 angle Video Dataset/Predicted_data3/frame16.jpg
./3 angle Video Dataset/Predicted_data3/frame17.jpg
./3 angle Video Dataset/Predicted_data3/frame18.jpg
./3 angle Video Datase

./3 angle Video Dataset/Predicted_data3/frame171.jpg
./3 angle Video Dataset/Predicted_data3/frame172.jpg
./3 angle Video Dataset/Predicted_data3/frame173.jpg
./3 angle Video Dataset/Predicted_data3/frame174.jpg
./3 angle Video Dataset/Predicted_data3/frame175.jpg
./3 angle Video Dataset/Predicted_data3/frame176.jpg
./3 angle Video Dataset/Predicted_data3/frame177.jpg
./3 angle Video Dataset/Predicted_data3/frame178.jpg
./3 angle Video Dataset/Predicted_data3/frame179.jpg
./3 angle Video Dataset/Predicted_data3/frame180.jpg
./3 angle Video Dataset/Predicted_data3/frame181.jpg
./3 angle Video Dataset/Predicted_data3/frame182.jpg
./3 angle Video Dataset/Predicted_data3/frame183.jpg
./3 angle Video Dataset/Predicted_data3/frame184.jpg
./3 angle Video Dataset/Predicted_data3/frame185.jpg
./3 angle Video Dataset/Predicted_data3/frame186.jpg
./3 angle Video Dataset/Predicted_data3/frame187.jpg
./3 angle Video Dataset/Predicted_data3/frame188.jpg
./3 angle Video Dataset/Predicted_data3/frame1

./3 angle Video Dataset/Predicted_data3/frame328.jpg
./3 angle Video Dataset/Predicted_data3/frame329.jpg
./3 angle Video Dataset/Predicted_data3/frame330.jpg
./3 angle Video Dataset/Predicted_data3/frame331.jpg
./3 angle Video Dataset/Predicted_data3/frame332.jpg
./3 angle Video Dataset/Predicted_data3/frame333.jpg
./3 angle Video Dataset/Predicted_data3/frame334.jpg
./3 angle Video Dataset/Predicted_data3/frame335.jpg
./3 angle Video Dataset/Predicted_data3/frame336.jpg
./3 angle Video Dataset/Predicted_data3/frame337.jpg
./3 angle Video Dataset/Predicted_data3/frame338.jpg
./3 angle Video Dataset/Predicted_data3/frame339.jpg
./3 angle Video Dataset/Predicted_data3/frame340.jpg
./3 angle Video Dataset/Predicted_data3/frame341.jpg
./3 angle Video Dataset/Predicted_data3/frame342.jpg
./3 angle Video Dataset/Predicted_data3/frame343.jpg
./3 angle Video Dataset/Predicted_data3/frame344.jpg
./3 angle Video Dataset/Predicted_data3/frame345.jpg
./3 angle Video Dataset/Predicted_data3/frame3

./3 angle Video Dataset/Predicted_data3/frame491.jpg
./3 angle Video Dataset/Predicted_data3/frame492.jpg
./3 angle Video Dataset/Predicted_data3/frame493.jpg
./3 angle Video Dataset/Predicted_data3/frame494.jpg
./3 angle Video Dataset/Predicted_data3/frame495.jpg
./3 angle Video Dataset/Predicted_data3/frame496.jpg
./3 angle Video Dataset/Predicted_data3/frame497.jpg
./3 angle Video Dataset/Predicted_data3/frame498.jpg
./3 angle Video Dataset/Predicted_data3/frame499.jpg
./3 angle Video Dataset/Predicted_data3/frame500.jpg
./3 angle Video Dataset/Predicted_data3/frame501.jpg
./3 angle Video Dataset/Predicted_data3/frame502.jpg
./3 angle Video Dataset/Predicted_data3/frame503.jpg
./3 angle Video Dataset/Predicted_data3/frame504.jpg
./3 angle Video Dataset/Predicted_data3/frame505.jpg
